### ISSUE TITLE
ML Practice Projects

### ISSUE THREAD

**Issue by JoycelynLongdon** [ai4er-cdt/resources#6]
Does anyone know any good ML projects to practice concepts we learn in lectures?

Deadline: Oct 2020

**Comment by mataln** [comment]
I've got something that I think should be pretty useful for getting on with now. I've been porting it to notebooks and doing it myself first to check it all seems ok. I should have a git repository ready tomorrow. Not sure if I should move it to a repository in ai4er-cdt rather than my personal page - most of the code is copied from the original lab

**Comment by mataln** [comment]
There's an example for logistic classification on the wiki now - it's not something we covered directly in lectures but it's pretty straightforward and I put some notes in with it. It's fairly short since we'll have the flood thing to do soon. I'll leave this issue open since hopefully there'll be more stuff to add in the future.
